/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Gabriela Mejía
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    private SistemaUsuarios sistemaUsuarios;
    private Usuario usuario;
    MenuInicio ventanaPrincipal;
    Configuracion config;

    public Configuracion(SistemaUsuarios sistemaUsuarios, MenuInicio ventanaPrincipal) {
        initComponents();
        this.sistemaUsuarios = sistemaUsuarios;
        this.ventanaPrincipal = ventanaPrincipal;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public void setSistemaUsuarios(SistemaUsuarios sistemaUsuarios) {
        this.sistemaUsuarios = sistemaUsuarios;
    }

    private void actualizarUsuario() {
        sistemaUsuarios.actualizarUsuario(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDifi = new javax.swing.JLabel();
        btnMJuego = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDifi.setForeground(new java.awt.Color(255, 255, 255));
        btnDifi.setText("Dificultad");
        btnDifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDifiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDifiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDifiMouseExited(evt);
            }
        });
        jPanel1.add(btnDifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        btnMJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnMJuego.setText("Modo de Juego");
        btnMJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMJuegoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMJuegoMouseExited(evt);
            }
        });
        jPanel1.add(btnMJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondos/confi.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDifiMouseClicked
        // TODO add your handling code here:
        Dificultad dificultad = new Dificultad(sistemaUsuarios, this, usuario);
        dificultad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDifiMouseClicked
    Color SELECT_COLOR = new Color(37, 203, 232);

    private void btnMJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMJuegoMouseClicked
        // TODO add your handling code here:
        ModoDeJuego modo = new ModoDeJuego(sistemaUsuarios, this, usuario);
        modo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMJuegoMouseClicked

    private void btnMJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMJuegoMouseEntered
        // TODO add your handling code here:
        btnMJuego.setForeground(SELECT_COLOR);
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_btnMJuegoMouseEntered

    private void btnMJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMJuegoMouseExited
        // TODO add your handling code here:
        btnMJuego.setForeground(Color.white);
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnMJuegoMouseExited

    private void btnDifiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDifiMouseEntered
        // TODO add your handling code here:
        btnDifi.setForeground(SELECT_COLOR);
        setCursor(Cursor.HAND_CURSOR);

    }//GEN-LAST:event_btnDifiMouseEntered

    private void btnDifiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDifiMouseExited
        // TODO add your handling code here:
        btnDifi.setForeground(Color.white);
        setCursor(Cursor.DEFAULT_CURSOR);

    }//GEN-LAST:event_btnDifiMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDifi;
    private javax.swing.JLabel btnMJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
