/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

/**
 *
 * @author Gabriela Mejía
 */
public class Dificultad extends javax.swing.JFrame {

    /**
     * Creates new form Dificultad
     */
    private SistemaUsuarios sistemaUsuarios;
    private Usuario usuario;
    MenuInicio ventanaPrincipal;
    Configuracion config;

    public Dificultad(SistemaUsuarios sistemaUsuarios, Configuracion config, Usuario usuario) {
        initComponents();
        this.sistemaUsuarios = sistemaUsuarios;
        this.config = config;
        this.usuario = usuario;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    private void actualizarUsuario() {
        sistemaUsuarios.actualizarUsuario(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNormal = new javax.swing.JButton();
        btnExpert = new javax.swing.JButton();
        btnGenius = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNormal.setText("NORMAL");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        btnExpert.setText("EXPERT");
        btnExpert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpertActionPerformed(evt);
            }
        });

        btnGenius.setText("GENIUS");
        btnGenius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeniusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExpert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnNormal)
                .addGap(18, 18, 18)
                .addComponent(btnExpert)
                .addGap(18, 18, 18)
                .addComponent(btnGenius)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        Usuario.ModoNormal = true;
        Usuario.ModoExpert = false;
        Usuario.ModoGenius = false;
        actualizarUsuario();
        config.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpertActionPerformed
        // TODO add your handling code here:
        Usuario.ModoNormal = false;
        Usuario.ModoExpert = true;
        Usuario.ModoGenius = false;
        actualizarUsuario();
        config.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnExpertActionPerformed

    private void btnGeniusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeniusActionPerformed
        // TODO add your handling code here:
        Usuario.ModoNormal = false;
        Usuario.ModoExpert = false;
        Usuario.ModoGenius = true;
        actualizarUsuario();
        config.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnGeniusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpert;
    private javax.swing.JButton btnGenius;
    private javax.swing.JButton btnNormal;
    // End of variables declaration//GEN-END:variables
}
