/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

/**
 *
 * @author Gabriela Mejía
 */
public class ModoDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form ModoDeJuego
     */
    private SistemaUsuarios sistemaUsuarios;
    private Usuario usuario;
    MenuInicio ventanaPrincipal;
    Configuracion config;

    public ModoDeJuego(SistemaUsuarios sistemaUsuarios, Configuracion config, Usuario usuario) {
        initComponents();
        this.sistemaUsuarios = sistemaUsuarios;
        this.config = config;
        this.usuario = usuario;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    private void actualizarUsuario() {
        sistemaUsuarios.actualizarUsuario(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAleatorio = new javax.swing.JLabel();
        btnManual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAleatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnAleatorio.setText("Modo Aleatorio");
        btnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAleatorioMouseClicked(evt);
            }
        });
        jPanel1.add(btnAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setText("Modo Manual");
        btnManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManualMouseClicked(evt);
            }
        });
        jPanel1.add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondos/confi2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualMouseClicked
        // TODO add your handling code here:
                Usuario.EsModoAleatorio = false;
        Usuario.EsModoManual = true;
        actualizarUsuario();
        config.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnManualMouseClicked

    private void btnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAleatorioMouseClicked
        // TODO add your handling code here:
                Usuario.EsModoAleatorio = true;
        Usuario.EsModoManual = false;
        actualizarUsuario();
        config.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnAleatorioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAleatorio;
    private javax.swing.JLabel btnManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}