/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import javax.swing.JComboBox;

/**
 *
 * @author Gabriela Mejía
 */
public class PartidaNueva extends javax.swing.JFrame {
    SistemaUsuarios sistemaUsuarios;
    Usuario player, contrincante; 
    JComboBox bandos;
    String bandoSeleccionado="Player1";
    Stats stats;
    MenuInicio mainWindow;
    /**
     * Creates new form PartidaNueva
     */
    public PartidaNueva(SistemaUsuarios sistemaUsuarios, Stats stats, MenuInicio mainWindow) {
        initComponents();
        this.stats = stats;
        this.mainWindow = mainWindow;
        this.sistemaUsuarios = sistemaUsuarios;
        this.player = sistemaUsuarios.getUsuarioActual();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void cargarUsuarios() {
        Usuario[] usuarios = sistemaUsuarios.getUsuariosActivos();
        System.out.println(usuarios.length);
        for (Usuario usuario : usuarios) {
            if (sistemaUsuarios.usuarioIniciado.getUsuario().equals(usuario.getUsuario())) continue;
            combobox.addItem(usuario.getUsuario());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (contrincante == null) {            
            String nombreUsuario = (String) combobox.getSelectedItem();
            contrincante = sistemaUsuarios.getUsuario(nombreUsuario);
            dispose();
            crearJuego();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void crearJuego() {
        Usuario player1, player2;
        if (bandoSeleccionado.equals("Player1")) {
            player1 = player;
            player2 = contrincante;
        }
        else {
            player1 = contrincante;
            player2 = player;
        }
        new Juego(sistemaUsuarios, stats, player1, player2, mainWindow);       
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}