/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JComboBox;

/**
 *
 * @author Gabriela Mejía
 */
public class PartidaNueva extends javax.swing.JFrame {

    SistemaUsuarios sistemaUsuarios;
    Usuario player, contrincante;
    JComboBox bandos;
    String bandoSeleccionado = "Player1";
    Stats stats;
    MenuInicio mainWindow;

    /**
     * Creates new form PartidaNueva
     */
    public PartidaNueva(SistemaUsuarios sistemaUsuarios, Stats stats, MenuInicio mainWindow) {
        initComponents();
        this.stats = stats;
        this.mainWindow = mainWindow;
        this.sistemaUsuarios = sistemaUsuarios;
        this.player = sistemaUsuarios.getUsuarioActual();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void cargarUsuarios() {
        Usuario[] usuarios = sistemaUsuarios.getUsuariosActivos();
        System.out.println(usuarios.length);
        for (Usuario usuario : usuarios) {
            if (sistemaUsuarios.usuarioIniciado.getUsuario().equals(usuario.getUsuario())) {
                continue;
            }
            combobox.addItem(usuario.getUsuario());
        }
    }
    Color SELECT_COLOR = new Color(37, 203, 232);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 344, -1, -1));

        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Jugar");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, -1));

        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        getContentPane().add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondos/PNueva.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        if (contrincante == null) {
            String nombreUsuario = (String) combobox.getSelectedItem();
            contrincante = sistemaUsuarios.getUsuario(nombreUsuario);
            dispose();
            crearJuego();
        }
    }//GEN-LAST:event_btnPlayMouseClicked

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboboxActionPerformed

    private void btnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseEntered
        // TODO add your handling code here:
        btnPlay.setForeground(SELECT_COLOR);
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_btnPlayMouseEntered

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        // TODO add your handling code here:
        btnPlay.setForeground(Color.white);
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnPlayMouseExited

    public void crearJuego() {
        Usuario player1, player2;
        if (bandoSeleccionado.equals("Player1")) {
            player1 = player;
            player2 = contrincante;
        } else {
            player1 = contrincante;
            player2 = player;
        }
        new Juego(sistemaUsuarios, stats, player1, player2, mainWindow);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnPlay;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
