/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriela Mejía
 */
public class RankingReportes extends javax.swing.JFrame {

    /**
     * Creates new form UniversoMarvel
     */
    
    SistemaUsuarios sistemaUsuarios;
    Stats stats;
    public RankingReportes(SistemaUsuarios sistemaUsuarios, Stats stats) {
        this.sistemaUsuarios = sistemaUsuarios;
        this.stats = stats;
        initComponents();
        cargarRankings();
        cargarPartidas();

        matchesLabel.setText("Partidas Jugadas: " + Stats.getPartidasJugadas());
    }
    public void cargarPartidas() {
        ArrayList<Partida> partidas = sistemaUsuarios.usuarioIniciado.getPartidas();
        DefaultTableModel model = (DefaultTableModel) juegosTabla.getModel();

        for (int i = (partidas.toArray().length - 1); i >= 0; i--) {
            Partida partida = partidas.get(i);
            String resultado;

            if (partida.puntosGanados == 1.5) {
                resultado = "EMPATE";
            } else {
                resultado = (partida.victoria) ? "VICTORIA" : "DERROTA";
            }

            model.addRow(new Object[]{partida.contrincante.getUsuario(), resultado,partida.mensajeGane, partida.fecha, partida.puntosGanados});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        matchTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        matchTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        matchesLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rankingTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        juegosTabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        matchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contrincante", "Resultado", "Fecha", "Puntos Ganados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(matchTable);

        matchTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contrincante", "Resultado", "Fecha", "Puntos Ganados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(matchTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Universo Marvel");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        matchesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matchesLabel.setForeground(new java.awt.Color(255, 255, 255));
        matchesLabel.setText("Partidas Jugadas");
        jPanel1.add(matchesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        rankingTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Usuario", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rankingTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(rankingTable1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESCRIPCIÓN DE MIS JUEGOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RANKING");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        juegosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contrincante", "Resultado", "Condición", "Fecha", "Puntos Que Obtuve"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        juegosTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(juegosTabla);
        if (juegosTabla.getColumnModel().getColumnCount() > 0) {
            juegosTabla.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondos/fondoRaRep.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void printUsuarios(Usuario[] usuarios) {
        for (Usuario user:usuarios) {
            System.out.println(user.getUsuario() + ": " + user.getPuntos());
        }
    }
    
    void cargarRankings() {
        Usuario[] usuarios = sistemaUsuarios.getUsuariosActivos();
        printUsuarios(usuarios);
        usuarios = ordernarUsuario(usuarios);
        System.out.println("===ORDENADOS===");
        printUsuarios(usuarios);
        
        DefaultTableModel model = (DefaultTableModel) rankingTable1.getModel();
        for (int i = 0; i<usuarios.length;i++) {
            Usuario user = usuarios[i];
            model.addRow(new Object[]{i+1, user.getUsuario(), user.getPuntos()});
        }
    }
    
    Usuario[] ordernarUsuario(Usuario[] usuarios) {
        Usuario usuariosOrdenados[] = Arrays.copyOf(usuarios, usuarios.length);
        
        if (usuarios.length == 1) return usuarios;
        
        for (int i =0;i<usuariosOrdenados.length-1;i++){
            Usuario L = usuarios[i];
            Usuario R = usuarios[i+1];
            if (L.getPuntos()<R.getPuntos()) {
                usuarios[i + 1] = L;
                usuarios[i] = R;
            }
        }
        return usuarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable juegosTabla;
    private javax.swing.JTable matchTable;
    private javax.swing.JTable matchTable1;
    private javax.swing.JLabel matchesLabel;
    private javax.swing.JTable rankingTable1;
    // End of variables declaration//GEN-END:variables
}
