/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriela Mejía
 */
public class RankingReportes extends javax.swing.JFrame {

    /**
     * Creates new form UniversoMarvel
     */
    
    SistemaUsuarios sistemaUsuarios;
    Stats stats;
    public RankingReportes(SistemaUsuarios sistemaUsuarios, Stats stats) {
        this.sistemaUsuarios = sistemaUsuarios;
        this.stats = stats;
        initComponents();
        cargarRankings();
        
        matchesLabel.setText("Partidas Jugadas: " + Stats.getPartidasJugadas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matchesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Universo Marvel");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RANKING");

        matchesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matchesLabel.setForeground(new java.awt.Color(255, 255, 255));
        matchesLabel.setText("Partidas Jugadas");

        rankingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Usuario", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rankingTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(rankingTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(425, 425, 425))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matchesLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(matchesLabel)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void printUsuarios(Usuario[] usuarios) {
        for (Usuario user:usuarios) {
            System.out.println(user.getUsuario() + ": " + user.getPuntos());
        }
    }
    
    void cargarRankings() {
        Usuario[] usuarios = sistemaUsuarios.getUsuariosActivos();
        printUsuarios(usuarios);
        usuarios = ordernarUsuario(usuarios);
        System.out.println("===ORDENADOS===");
        printUsuarios(usuarios);
        
        DefaultTableModel model = (DefaultTableModel) rankingTable.getModel();
        for (int i = 0; i<usuarios.length;i++) {
            Usuario user = usuarios[i];
            model.addRow(new Object[]{i+1, user.getUsuario(), user.getPuntos()});
        }
    }
    
    Usuario[] ordernarUsuario(Usuario[] usuarios) {
        Usuario usuariosOrdenados[] = Arrays.copyOf(usuarios, usuarios.length);
        
        if (usuarios.length == 1) return usuarios;
        
        for (int i =0;i<usuariosOrdenados.length-1;i++){
            Usuario L = usuarios[i];
            Usuario R = usuarios[i+1];
            if (L.getPuntos()<R.getPuntos()) {
                usuarios[i + 1] = L;
                usuarios[i] = R;
            }
        }
        return usuarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel matchesLabel;
    private javax.swing.JTable rankingTable;
    // End of variables declaration//GEN-END:variables
}
