/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ghosts;

import java.awt.Color;

/**
 *
 * @author Gabriela Mejía
 */
public class VentanaCombate extends javax.swing.JPanel {

    /**
     * Creates new form VentanaCombate
     */
    public VentanaCombate(Personaje atacante, Personaje defensor, int ganaAtacante) {
        initComponents();
        empateLabel.setVisible(false);
        
        // Poner imágenes
        jLabel1.setIcon(atacante.icono);
        defensorIcon.setIcon(defensor.icono);

        // El atacante siempre es el ganador
        atacanteLabel.setText("GANADOR");
        defensorLabel.setText("PERDEDOR");

        atacanteLabel.setForeground(Color.green);
        defensorLabel.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atacanteLabel = new javax.swing.JLabel();
        defensorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        defensorIcon = new javax.swing.JLabel();

        atacanteLabel.setText("GANADOR");

        defensorLabel.setText("PERDEDOR");

        jLabel3.setText("VS");

        empateLabel.setText("EMPATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(defensorIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(atacanteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(defensorLabel)))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(empateLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(defensorIcon))
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atacanteLabel)
                    .addComponent(defensorLabel))
                .addGap(36, 36, 36)
                .addComponent(empateLabel)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atacanteLabel;
    private javax.swing.JLabel defensorIcon;
    private javax.swing.JLabel defensorLabel;
    private javax.swing.JLabel empateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}